import { setGlobalOptions } from 'firebase-functions/v2';
import {
  adminSetUserMemberships,
  adminUpdateInstructorProfile,
  adminUpdateStudentProfile,
  adminUpdateStudentTimeline,
  approveGraduationRequest,
  approveJoinRequest,
  assignUserToAcademy,
  createAcademy,
  createUserWithRole,
  deactivateStudent,
  deleteMyAccount,
  getPublicSignupAcademies,
  listSignupAcademies,
  rejectJoinRequest,
  reactivateStudent,
  requestAdditionalAcademy,
  requestReactivation,
  resolveReactivationRequest,
  setStudentAttendanceBonus,
  setUserRole,
  switchActiveAcademy,
  syncOwnUserEmail,
  submitStudentSignup,
  transferJoinRequest,
  updateJoinRequest,
  updateOwnStudentProfile,
  updateOwnStaffBeltGrade,
  updateStudentBeltGrade,
  validateSessionAccess,
} from './modules/auth';
import {
  createClassScheduleBatch,
  deleteClassSchedule,
  generateClassQrCode,
  finishClassSession,
  startClassSession,
  updateRecurringClassSeries,
  upsertClassSchedule,
} from './modules/classes';
import {
  approveAttendanceRequest,
  onAttendanceCreated,
  onAttendanceDeleted,
  rejectAttendanceRequest,
  registerAttendance,
  removeAttendance,
  submitAttendanceRequest,
} from './modules/attendance';
import {
  approveFightVideoSubmission,
  rejectFightVideoSubmission,
  submitFightVideoSubmission,
} from './modules/fightVideos';
import {
  adjustProductStock,
  cancelFinanceSale,
  cancelStockWithdrawal,
  createFinanceSale,
  createStockWithdrawal,
  settleStockWithdrawal,
  deleteOrArchiveFinanceProduct,
  deleteOrArchiveFinanceService,
  markExpensePaid,
  recordSalePayment,
  updateFinanceSale,
  upsertExpense,
  upsertFinanceProduct,
  upsertFinanceService,
  upsertManualRevenue,
} from './modules/finance';
import {
  evaluateUserProgression,
  rebuildUserDerivedState,
  repairAcademyProgressionRules,
  upsertAcademyProgressionRules,
} from './modules/progression';
import {
  onFightWritten,
  recalculateAcademyRankings,
  recalculateUserRanking,
} from './modules/ranking';
import {
  syncUserMissionProgress,
  upsertMission,
} from './modules/missions';
import {
  backfillLearningAudience,
  deleteLearningCourse,
  deleteLearningLesson,
  deleteLearningTrack,
  markLearningBlockComplete,
  recordLessonPlayback,
  recordLearningBlockPlayback,
  replaceLearningLessonBlocks,
  startLessonQuiz,
  submitLessonQuiz,
  upsertLearningCourse,
  upsertLearningLesson,
  upsertLearningTrack,
  upsertLessonQuiz,
} from './modules/learning';
import { callableProxy } from './modules/proxy';
import {
  clearGraduationRequests,
  clearNotifications,
  markNotificationRead,
  repairPendingGraduationNotifications,
  registerDeviceToken,
  sendSegmentedNotification,
} from './modules/notifications';
import { toggleClassRsvp } from './modules/rsvp';

setGlobalOptions({
  region: 'southamerica-east1',
  // Cada chamada do frontend consome duas instancias: o `callableProxy` segura
  // uma enquanto aguarda a callable de destino, que ocupa outra. Com o teto em
  // 10 a capacidade real era de 5 pedidos simultaneos, e o Cloud Run passava a
  // responder 429 (resource-exhausted) em horario de pico.
  maxInstances: 32,
});

export {
  adminUpdateInstructorProfile,
  adjustProductStock,
  approveGraduationRequest,
  deactivateStudent,
  deleteMyAccount,
  reactivateStudent,
  requestAdditionalAcademy,
  requestReactivation,
  resolveReactivationRequest,
  clearGraduationRequests,
  clearNotifications,
  repairPendingGraduationNotifications,
  adminSetUserMemberships,
  approveJoinRequest,
  approveAttendanceRequest,
  approveFightVideoSubmission,
  assignUserToAcademy,
  callableProxy,
  cancelFinanceSale,
  createAcademy,
  createClassScheduleBatch,
  createFinanceSale,
  createUserWithRole,
  createUserWithRole as createUser,
  deleteClassSchedule,
  backfillLearningAudience,
  deleteLearningCourse,
  deleteLearningLesson,
  deleteLearningTrack,
  deleteOrArchiveFinanceProduct,
  deleteOrArchiveFinanceService,
  evaluateUserProgression,
  finishClassSession,
  generateClassQrCode,
  getPublicSignupAcademies,
  listSignupAcademies,
  markExpensePaid,
  markNotificationRead,
  markLearningBlockComplete,
  onAttendanceCreated,
  onAttendanceDeleted,
  onFightWritten,
  recalculateAcademyRankings,
  recalculateUserRanking,
  recordSalePayment,
  cancelStockWithdrawal,
  createStockWithdrawal,
  settleStockWithdrawal,
  recordLessonPlayback,
  recordLearningBlockPlayback,
  rejectAttendanceRequest,
  rejectFightVideoSubmission,
  rejectJoinRequest,
  rebuildUserDerivedState,
  repairAcademyProgressionRules,
  registerAttendance,
  removeAttendance,
  registerDeviceToken,
  replaceLearningLessonBlocks,
  sendSegmentedNotification,
  setStudentAttendanceBonus,
  setUserRole,
  switchActiveAcademy,
  syncOwnUserEmail,
  startLessonQuiz,
  startClassSession,
  submitAttendanceRequest,
  submitFightVideoSubmission,
  submitStudentSignup,
  submitLessonQuiz,
  syncUserMissionProgress,
  toggleClassRsvp,
  transferJoinRequest,
  updateFinanceSale,
  updateJoinRequest,
  updateRecurringClassSeries,
  adminUpdateStudentProfile,
  adminUpdateStudentTimeline,
  upsertExpense,
  updateOwnStudentProfile,
  updateOwnStaffBeltGrade,
  updateStudentBeltGrade,
  upsertAcademyProgressionRules,
  upsertClassSchedule,
  upsertFinanceProduct,
  upsertFinanceService,
  upsertLearningCourse,
  upsertLearningLesson,
  upsertLearningTrack,
  upsertLessonQuiz,
  upsertManualRevenue,
  upsertMission,
  validateSessionAccess,
};
