import { setGlobalOptions } from 'firebase-functions/v2';
import {
  adminUpdateStudentProfile,
  adminUpdateStudentTimeline,
  approveGraduationRequest,
  approveJoinRequest,
  assignUserToAcademy,
  createAcademy,
  createUserWithRole,
  getPublicSignupAcademies,
  listSignupAcademies,
  rejectJoinRequest,
  setStudentAttendanceBonus,
  setUserRole,
  syncOwnUserEmail,
  submitStudentSignup,
  updateOwnStudentProfile,
  updateStudentBeltGrade,
  validateSessionAccess,
} from './modules/auth';
import {
  createClassScheduleBatch,
  deleteClassSchedule,
  generateClassQrCode,
  finishClassSession,
  startClassSession,
  updateRecurringClassSeries,
  upsertClassSchedule,
} from './modules/classes';
import {
  approveAttendanceRequest,
  onAttendanceCreated,
  onAttendanceDeleted,
  rejectAttendanceRequest,
  registerAttendance,
  removeAttendance,
  submitAttendanceRequest,
} from './modules/attendance';
import {
  approveFightVideoSubmission,
  rejectFightVideoSubmission,
  submitFightVideoSubmission,
} from './modules/fightVideos';
import {
  evaluateUserProgression,
  rebuildUserDerivedState,
  repairAcademyProgressionRules,
  upsertAcademyProgressionRules,
} from './modules/progression';
import {
  onFightWritten,
  recalculateAcademyRankings,
  recalculateUserRanking,
} from './modules/ranking';
import {
  syncUserMissionProgress,
  upsertMission,
} from './modules/missions';
import {
  markLearningBlockComplete,
  recordLessonPlayback,
  recordLearningBlockPlayback,
  replaceLearningLessonBlocks,
  startLessonQuiz,
  submitLessonQuiz,
  upsertLearningCourse,
  upsertLearningLesson,
  upsertLearningTrack,
  upsertLessonQuiz,
} from './modules/learning';
import { callableProxy } from './modules/proxy';
import {
  markNotificationRead,
  registerDeviceToken,
  sendSegmentedNotification,
} from './modules/notifications';
import { toggleClassRsvp } from './modules/rsvp';

setGlobalOptions({
  region: 'southamerica-east1',
  maxInstances: 10,
});

export {
  approveGraduationRequest,
  approveJoinRequest,
  approveAttendanceRequest,
  approveFightVideoSubmission,
  assignUserToAcademy,
  callableProxy,
  createAcademy,
  createClassScheduleBatch,
  createUserWithRole,
  createUserWithRole as createUser,
  deleteClassSchedule,
  evaluateUserProgression,
  finishClassSession,
  generateClassQrCode,
  getPublicSignupAcademies,
  listSignupAcademies,
  markNotificationRead,
  markLearningBlockComplete,
  onAttendanceCreated,
  onAttendanceDeleted,
  onFightWritten,
  recalculateAcademyRankings,
  recalculateUserRanking,
  recordLessonPlayback,
  recordLearningBlockPlayback,
  rejectAttendanceRequest,
  rejectFightVideoSubmission,
  rejectJoinRequest,
  rebuildUserDerivedState,
  repairAcademyProgressionRules,
  registerAttendance,
  removeAttendance,
  registerDeviceToken,
  replaceLearningLessonBlocks,
  sendSegmentedNotification,
  setStudentAttendanceBonus,
  setUserRole,
  syncOwnUserEmail,
  startLessonQuiz,
  startClassSession,
  submitAttendanceRequest,
  submitFightVideoSubmission,
  submitStudentSignup,
  submitLessonQuiz,
  syncUserMissionProgress,
  toggleClassRsvp,
  updateRecurringClassSeries,
  adminUpdateStudentProfile,
  adminUpdateStudentTimeline,
  updateOwnStudentProfile,
  updateStudentBeltGrade,
  upsertAcademyProgressionRules,
  upsertClassSchedule,
  upsertLearningCourse,
  upsertLearningLesson,
  upsertLearningTrack,
  upsertLessonQuiz,
  upsertMission,
  validateSessionAccess,
};
